name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js version 8
      # using setup-node action which has node-version as argument
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
        #default is 10.. I'm trying 8 ;D
    - name: build and run test during PR.
      run:
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
